FROM quay.io/hummingbird/python:latest-builder
USER 0
RUN dnf install -y python3-numpy && dnf clean all
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py ./
USER 1001
EXPOSE 8080
CMD ["python3", "./app.py"]